[package]
name = "tarkov_multi"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

[profile.release]
opt-level = 3